version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "cy-takeuchi"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "cy-takeuchi"
    commit-message:
      prefix: "fix"
    groups:
      group-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
